image: python:3.11.3

stages:
  - build
  - test
  - report

variables:
  PYTHON_VERSION: "3.11.3"

before_script:
  - python --version

build:
  stage: build
  script:
    - apt-get update
    - apt-get install libgl1 -y
    - git submodule update --init --recursive
    - python -m venv ./venv
    - . ./venv/bin/activate
    - pip install -r yolov7/requirements.txt
    - deactivate

test:
  stage: test
  script:
    - . ./venv/bin/activate
    - python tests.py
    - deactivate

report:
  stage: report
  script:
    - ls
    - ls venv/
    - . ./venv/bin/activate
    - pip install pytest-cov
    - pytest --cov=tests --cov-report=html
    - deactivate
  artifacts:
    paths:
      - ./tests/htmlcov/

cache:
  paths:
    - venv/
