image: python:3.11.3

stages:
  - build
  - test
  - report

variables:
  PYTHON_VERSION: "3.11.3"

before_script:
  - apt-get update
  - apt-get install libgl1 -y
  - python -m venv ./venv
  - . ./venv/bin/activate

build:
  stage: build
  script:
    - git submodule update --init --recursive
    - pip install -r yolov7/requirements.txt
    - pip freeze > requirements.txt

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - python tests.py

report:
  stage: report
  script:
    - pip install pytest-cov
    - pytest --cov=tests --cov-report=html
  artifacts:
    paths:
      - ./tests/htmlcov/
