image: python:3.11.3

stages:
  - build
  - test

variables:
  PYTHON_VERSION: "3.11.3"

before_script:
  - python --version

build:
  stage: build
  script:
    - python -m venv ./venv
    - . ./venv/bin/activate
    - git submodule update --init --recursive
    - pip install -r yolov7/requirements.txt
    - deactivate

test:
  stage: test
  script:
    - . ./venv/bin/activate
    - python tests.py
    - deactivate
