image: python:3.11.3

stages:
  - build
  - test
  - report

variables:
  PYTHON_VERSION: "3.11.3"

before_script:
  - apt-get update
  - apt-get install libgl1 -y
  - python -m venv ./venv
  - . ./venv/bin/activate
  - git submodule update --init --recursive
  - pip install -r yolov7/requirements.txt
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - pip install pytest
    - export PYTHONPATH=./:./yolov7:$PYTHONPATH
    - pytest --junitxml=reports/test-report.xml tests.py
  artifacts:
    reports:
      junit: reports/test-report.xml
